# Generated by Django 2.1.2 on 2019-05-11 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1)),
                ('tipagem', models.CharField(choices=[('A', 'Abate'), ('M', 'Matriz')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('date_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.Creator')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='fazenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.Farm'),
        ),
    ]
