# Generated by Django 2.1.2 on 2019-05-11 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='sexo',
            field=models.CharField(choices=[('Macho', 'M'), ('Fêmea', 'F')], max_length=1),
        ),
        migrations.AlterField(
            model_name='animal',
            name='tipagem',
            field=models.CharField(choices=[('Abate', 'A'), ('Matriz', 'M')], max_length=1),
        ),
    ]
