# Generated by Django 2.1.2 on 2019-05-11 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_auto_20190511_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='sexo',
            field=models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1),
        ),
        migrations.AlterField(
            model_name='animal',
            name='tipagem',
            field=models.CharField(choices=[('A', 'Abate'), ('M', 'Matriz')], max_length=1),
        ),
    ]
